"""Add CompanyAnalysis model for AI company website analysis

Revision ID: cf3f9d6d0d0a
Revises: 
Create Date: 2026-01-01 01:37:35.613971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3f9d6d0d0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=False),
    sa.Column('company_url', sa.String(length=500), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('target_customers', sa.Text(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cache_hit_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_analysis_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_analysis_company_domain'), ['company_domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_analysis_expires_at'), ['expires_at'], unique=False)

    op.create_table('salon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_hpb', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('place_id', sa.String(length=100), nullable=True),
    sa.Column('cid', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('inquiry_url', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('hotpepper_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cid'),
    sa.UniqueConstraint('hotpepper_url'),
    sa.UniqueConstraint('place_id')
    )
    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salon_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_salon_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_salon_name_hpb'), ['name_hpb'], unique=False)

    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('salary', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'source_name', name='_salon_source_uc')
    )
    op.create_table('salon_categories',
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('salon_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salon_categories')
    op.drop_table('review_summary')
    op.drop_table('job')
    op.drop_table('coupon')
    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salon_name_hpb'))
        batch_op.drop_index(batch_op.f('ix_salon_name'))
        batch_op.drop_index(batch_op.f('ix_salon_address'))

    op.drop_table('salon')
    with op.batch_alter_table('company_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_analysis_expires_at'))
        batch_op.drop_index(batch_op.f('ix_company_analysis_company_domain'))
        batch_op.drop_index(batch_op.f('ix_company_analysis_analyzed_at'))

    op.drop_table('company_analysis')
    op.drop_table('category')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
